#!/bin/sh
set -e
htpasswd -cb /pass/nginx $1 $2 > /dev/null
mosquitto_passwd -b /pass/passwd $1 $2 > /dev/null
ALLPROCESSES=$(ps aux)
PID=$(echo "$ALLPROCESSES" | grep mosquitto | awk '{ print $1 }')
kill -1 $PID  > /dev/null
echo "DONE"